### ISSUE TITLE
Implement verbose command line arg on pldm daemon

### ISSUE THREAD

**Issue by dkodihal** [openbmc/pldm#7] opened 2019-07-01 18:10 UTC
Currently the pldm daemon has a way to enable verbose logging via a configure flag, however a runtime verbose command line arg will prove more helpful - that way the daemon can quickly be restarted to enable/disable verbose logging without having to rebuild it.

This issue is to replace the build time verbose logging enablement by runtime verbose enablement.

One way is to do this `pldmd -v/--verbose $VERBOSE`, where `$VERBOSE` is defined as a sytemd env file, with 0 being no verbosity and 1 being full verbosity. Verbose logs can then be printed only if --verbose was passed as 1.

**Comment by dkodihal** [comment] 2019-07-01 18:10
@jinuthomas can you work on this please?

**Comment by manojkiraneda** [comment] 2022-07-18 02:08
@tomjoseph83 @dkodihal @sampmisr can we close this , as i see this has been unstreamed with https://github.com/openbmc/pldm/commit/75dd4427bf319a8fd28d549eff027e0275d07c80

**Comment by amboar** [comment] 2022-07-18 02:10
> @tomjoseph83 @dkodihal @sampmisr can we close this , as i see this has been unstreamed with [75dd442](https://github.com/openbmc/pldm/commit/75dd4427bf319a8fd28d549eff027e0275d07c80)

The implementation feels a little like it runs afoul of https://github.com/openbmc/docs/blob/master/anti-patterns.md#non-standard-debug-application-options-and-logging :(

**Comment by manojkiraneda** [comment] 2022-07-18 02:28
> > @tomjoseph83 @dkodihal @sampmisr can we close this , as i see this has been unstreamed with [75dd442](https://github.com/openbmc/pldm/commit/75dd4427bf319a8fd28d549eff027e0275d07c80)
> 
> The implementation feels a little like it runs afoul of https://github.com/openbmc/docs/blob/master/anti-patterns.md#non-standard-debug-application-options-and-logging :(

The issue here is that we are using std::cout ? instead of `DEBUG` logging API's ? because the resolution did mention that apps could support --verbose as a means to control the flood of journal logs (similar to what was being implemented)
> If an OpenBMC application is to support enhanced debug via a command line then it will support the standard "-v,--verbose" option. In general, OpenBMC developers should utilize the "debug" journald level for debug messages. This can be enabled/disabled globally and would apply to all applications. If a developer believes this would cause too much debug data in certain cases then they can protect these journald debug calls around a --verbose command line option.

**Comment by amboar** [comment] 2022-07-18 02:31
No, the issue is that you require an argument to `--verbose`. `--verbose 0` being not verbose isn't particularly intuitive. Why not just not pass the `--verbose` option at all if you don't want verbosity? Similarly, if you do want verbose output, just pass `--verbose`? No need for `0` and `1`.

**Comment by manojkiraneda** [comment] 2022-07-18 02:35
> No, the issue is that you require an argument to `--verbose`. `--verbose 0` being not verbose isn't particularly intuitive. Why not just not pass the `--verbose` option at all if you don't want verbosity? Similarly, if you do want verbose output, just pass `--verbose`? No need for `0` and `1`.

ah got you , and yes that makes sense.

**Comment by tomjoseph83** [comment] 2022-07-18 05:20
Yes makes sense, @manojkiraneda feel free to push a patch.

**Comment by manojkiraneda** [comment] 2022-09-10 10:10
@tomjoseph83 @amboar tried to push a patch at https://gerrit.openbmc.org/c/openbmc/pldm/+/57064, please review.

**Closed** 2022-09-21 06:03 UTC
